# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, performs a Codacy security scan
# and integrates the results with the
# GitHub Advanced Security code scanning feature.  For more information on
# the Codacy security scan action usage and parameters, see
# https://github.com/codacy/codacy-analysis-cli-action.
# For more information on Codacy Analysis CLI in general, see
# https://github.com/codacy/codacy-analysis-cli.

name: Codacy Security Scan

on:
  push:
    branches: ['main']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  schedule:
    - cron: '20 14 * * 1'

permissions:
  contents: read

jobs:
  php-lint:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint PHP
        # You may pin to the exact commit or the version.
        # uses: Firehed/lint-php-action@4e424397e74b38eae09f1cc32621c2f2a65e537a
        uses: Firehed/lint-php-action@v1
        with:
          # Version of PHP
          php-version: latest
